version: "3"

services:
  # API
  mysql-users:
    image: ${TIX_USER_DB}
    env_file: mysql_secret_users.env
    volumes:
      - mysql-data-users:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "${TIX_API_MYSQL_USERS_PORT}:3306"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.userdb==true

  mysql-stats:
    image: ${TIX_STAT_DB}
    env_file: mysql_secret_stats.env
    volumes:
      - mysql-data-stats:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "${TIX_API_MYSQL_STATS_PORT}:3306"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.statdb==true

  tix-api:
    image: "${TIX_IMAGE_API}"
    environment:
      TIX_API_PUBLIC_URL: ${TIX_API_PUBLIC_HOST}
      TIX_API_MYSQL_USERS_HOST: ${TIX_API_MYSQL_USERS_HOST}
      TIX_API_MYSQL_STATS_HOST: ${TIX_API_MYSQL_STATS_HOST}
    ports:
      - "${TIX_API_PUBLIC_PORT}:3001/tcp"
    depends_on:
      - mysql-users
      - mysql-stats
    command: ["./wait-for-it.sh", "mysql-users:3306", "--", "npm", "start"]

  tix-ip-to-as:
    image: "${TIX_IMAGE_IPTOAS}"
    env_file:
      - mysql_secret_users.env
    environment:
      MYSQL_DATABASE: ${TIX_MYSQL_DATABASE}
      MYSQL_HOST: ${TIX_MYSQL_HOST}
    depends_on:
      - mysql-users
    volumes:
      - iptoas-data:/root/iptoas/files
    deploy:
      replicas: 0

  # Web
  tix-web:
    image: "${TIX_IMAGE_WEB}"
    ports:
      - "${TIX_WEB_PUBLIC_PORT}:${TIX_WEB_PUBLIC_PORT}/tcp"
    environment:
      TIX_WEB_HOST: ${TIX_WEB_PUBLIC_HOST}
      TIX_WEB_PORT: ${TIX_WEB_PUBLIC_PORT}
      TIX_WEB_API_URL: http://${TIX_API_PUBLIC_HOST}:${TIX_API_PUBLIC_PORT}/api
    command: ["./run.sh"]

  # Time
  rabbitmq:
    image: "rabbitmq:3.6.12-management-alpine"
    env_file: 
      - rabbitmq_secret.env
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    expose:
      - "5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.rabbit==true

  tix-time-server:
    image: "${TIX_IMAGE_TIME_SERVER}"
    env_file:
      - rabbitmq_secret.env
    environment:
      TIX__WORKER_THREADS_QUANTITY: 16
      TIX__QUEUE__HOST: ${TIX_RABBITMQ_HOST}
      TIX__QUEUE__NAME: ${TIX_SERVER_CONDENSER_QUEUE}
      TIX__LOG_LEVEL: ${LOG_LEVEL}
      TIX__UDP_PORT: 4500
      TIX__HTTP_PORT: 8080
      TIMEOUT: ${TIX_RABBITMQ_TIMEOUT}
    ports:
      - "4500:4500/udp"
      - "18080:8080"
    depends_on:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]

  tix-time-condenser:
    image: "${TIX_IMAGE_TIME_CONDENSER}"
    env_file:
      - rabbitmq_secret.env
    environment:
      SPRING_RABBITMQ_HOST: ${TIX_RABBITMQ_HOST}
      TIX_CONDENSER_TIX_API_HTTPS: ${TIX_API_INTERNAL_SSL}
      TIX_CONDENSER_TIX_API_HOST: ${TIX_API_INTERNAL_HOST}
      TIX_CONDENSER_TIX_API_PORT: ${TIX_API_INTERNAL_PORT}
      TIX_CONDENSER_QUEUES_RECEIVING_NAME: ${TIX_SERVER_CONDENSER_QUEUE}
      TIX_CONDENSER_QUEUES_SENDING_NAME: ${TIX_CONDENSER_PROCESSOR_QUEUE}
      TIMEOUT: ${TIX_RABBITMQ_TIMEOUT}
    volumes:
      - reports-data:/tmp/reports
    depends_on:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.condenser==true
    
  tix-time-processor:
    image: "${TIX_IMAGE_TIME_PROCESSOR}"
    env_file:
      - rabbitmq_secret.env
    environment:
      LOGGING_LEVEL_ORG_SLF4J: ${LOG_LEVEL}
      TIX_RABBITMQ_HOST: ${TIX_RABBITMQ_HOST}
      TIX_API_SSL: ${TIX_API_INTERNAL_SSL}
      TIX_API_HOST: ${TIX_API_INTERNAL_HOST}
      TIX_API_PORT: ${TIX_API_INTERNAL_PORT}
      TIX_CONDENSER_PROCESSOR_QUEUE: ${TIX_CONDENSER_PROCESSOR_QUEUE}
      TIMEOUT: ${TIX_RABBITMQ_TIMEOUT}
    depends_on:
      - tix-api
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]
    deploy:
      replicas: 5

volumes:
  rabbitmq-data:
  mysql-data-stats:
  mysql-data-users:
  iptoas-data:
  reports-data:
