version: "3"

services:
  # API
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    ports:
      - 6603:3306
    env_file: tix.env
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

  tix-api:
    image: "${TIX_IMAGE_SOURCE}/tix-api"
    ports:
      - "3001:3001/tcp"
    links:
      - mysql

  tix-ip-to-as:
    image: "${TIX_IMAGE_SOURCE}/tix-ip-to-as"
    links:
      - mysql
    volumes:
      - /storage/docker/iptoas-datadir:/root/iptoas/files

  tix-web:
    image: "${TIX_IMAGE_SOURCE}/tix-web"
    ports:
      - "3000:3000/tcp"
    env_file: tix.env

  # Time
  rabbitmq:
    image: "rabbitmq:3.6.12-management-alpine"
    hostname: "tix-time-rabbitmq"
    env_file: tix.env
    ports:
      - "127.0.0.1:15673:15672"
      - "127.0.0.1:5672:5672"
    expose:
      - "5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  tix-time-server:
    image: "${TIX_IMAGE_SOURCE}/tix-time-server"
    env_file: tix.env
    environment:
      - TIX__ENVIRONMENT=stage
    ports:
      - "4500:4500/udp"
      - "127.0.0.1:18080:8080"
    links:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]

  tix-time-condenser:
    image: "${TIX_IMAGE_SOURCE}/tix-time-condenser"
    env_file: tix.env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
    volumes:
      - reports-data:/tmp/reports
    links:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]

  tix-time-processor-beat:
    image: "${TIX_IMAGE_SOURCE}/tix-time-processor"
    env_file: tix.env
    environment:
      - PROCESSOR_TYPE=BEAT
    volumes:
      - celery-scheduler-data:/tmp/celerybeat-schedule.d
    links:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]
    
  tix-time-processor-worker:
    image: "${TIX_IMAGE_SOURCE}/tix-time-processor"
    env_file: tix.env
    environment:
      - PROCESSOR_TYPE=WORKER
    volumes:
      - reports-data:/tmp/reports
      - celery-scheduler-data:/tmp/celerybeat-schedule.d
    links:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]

volumes:
  reports-data:
  celery-scheduler-data:
  rabbitmq-data:
