version: "3"

services:
  # API
  mysql:
    image: mysql:5.7
    env_file:
      - mysql_secret.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${TIX_MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql

  tix-api:
    image: "${TIX_IMAGE_API}"
    environment:
      TIX_API_PUBLIC_URL: ${TIX_API_PUBLIC_HOST}
    ports:
      - "${TIX_API_PUBLIC_PORT}:3001/tcp"
    links:
      - mysql

  tix-ip-to-as:
    image: "${TIX_IMAGE_IPTOAS}"
    env_file:
      - mysql_secret.env
    environment:
      MYSQL_DATABASE: ${TIX_MYSQL_DATABASE}
      MYSQL_HOST: ${TIX_MYSQL_HOST}
    links:
      - mysql
    volumes:
      - iptoas-data:/root/iptoas/files

  # Web
  tix-web:
    image: "${TIX_IMAGE_WEB}"
    ports:
      - "${TIX_WEB_PUBLIC_PORT}:3000/tcp"
    environment:
      TIX_WEB_HOST: ${TIX_WEB_PUBLIC_HOST}
      TIX_WEB_PORT: ${TIX_WEB_PUBLIC_PORT}
      TIX_WEB_API_URL: http://${TIX_API_PUBLIC_HOST}:${TIX_API_PUBLIC_PORT}/api
    command: ["./run.sh"]

  # Time
  rabbitmq:
    image: "rabbitmq:3.6.12-management-alpine"
    env_file: 
      - rabbitmq_secret.env
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    expose:
      - "5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  tix-time-server:
    image: "${TIX_IMAGE_TIME_SERVER}"
    env_file:
      - rabbitmq_secret.env
    environment:
      TIX__WORKER_THREADS_QUANTITY: 16
      TIX__QUEUE__HOST: ${TIX_RABBITMQ_HOST}
      TIX__QUEUE__NAME: ${TIX_SERVER_CONDENSER_QUEUE}
      TIX__LOG_LEVEL: ${LOG_LEVEL}
      TIX__UDP_PORT: 4500
      TIX__HTTP_PORT: 8080
    ports:
      - "4500:4500/udp"
      - "127.0.0.1:18080:8080"
    links:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]

  tix-time-condenser:
    image: "${TIX_IMAGE_TIME_CONDENSER}"
    env_file:
      - rabbitmq_secret.env
    environment:
      SPRING_RABBITMQ_HOST: ${TIX_RABBITMQ_HOST}
      TIX_CONDENSER_TIX_API_HTTPS: ${TIX_API_INTERNAL_SSL}
      TIX_CONDENSER_TIX_API_HOST: ${TIX_API_INTERNAL_HOST}
      TIX_CONDENSER_TIX_API_PORT: ${TIX_API_INTERNAL_PORT}
      TIX_CONDENSER_QUEUES_RECEIVING_NAME: ${TIX_SERVER_CONDENSER_QUEUE}
    volumes:
      - reports-data:/tmp/reports
    links:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]

  tix-time-processor-beat:
    image: "${TIX_IMAGE_TIME_PROCESSOR}"
    env_file:
      - rabbitmq_secret.env
    environment:
      PROCESSOR_TYPE: BEAT
      TIX_RABBITMQ_HOST: ${TIX_RABBITMQ_HOST}
    volumes:
      - celery-scheduler-data:/tmp/celerybeat-schedule.d
    links:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]
    
  tix-time-processor-worker:
    image: "${TIX_IMAGE_TIME_PROCESSOR}"
    env_file:
      - rabbitmq_secret.env
    environment:
      PROCESSOR_TYPE: WORKER
      TIX_LOG_LEVEL: ${LOG_LEVEL}
      TIX_RABBITMQ_HOST: ${TIX_RABBITMQ_HOST}
      TIX_API_SSL: ${TIX_API_INTERNAL_SSL}
      TIX_API_HOST: ${TIX_API_INTERNAL_HOST}
      TIX_API_PORT: ${TIX_API_INTERNAL_PORT}
    volumes:
      - reports-data:/tmp/reports
      - celery-scheduler-data:/tmp/celerybeat-schedule.d
    links:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "-s", "--", "./run.sh"]

volumes:
  celery-scheduler-data:
  rabbitmq-data:
  mysql-data:
  iptoas-data:
  reports-data:
